name: 'Hostloc Auto Get Points'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Get points'
      run: python hostloc_get_points.py
